from enum import Enum, auto
from io import BytesIO
from pathlib import Path
from typing import List, Union, Tuple, Any, Dict, Sequence

import polars as pl

class Strand(Enum):
    Forward = auto()
    Reverse = auto()
    Null = auto()

    @property
    def name(self) -> str: ...

class Context(Enum):
    CG = auto()
    CHG = auto()
    CHH = auto()

    @property
    def name(self) -> str: ...

class BsxColumns(Enum):
    Chr = auto()
    Position = auto()
    Strand = auto()
    Context = auto()
    CountM = auto()
    CountTotal = auto()
    Density = auto()

    @staticmethod
    def schema() -> pl.Schema: ...
    def as_str(self) -> str: ...
    @staticmethod
    def colnames() -> List[str]: ...
    @staticmethod
    def has_name(name: str) -> bool: ...
    def __str__(self): ...
    def __repr__(self): ...

class AggMethod(Enum):
    Mean = auto()
    GeometricMean = auto()
    Median = auto()
    Max = auto()
    Min = auto()

class BsxBatch:
    def __init__(
        self,
        chr: str,
        chr_dtype: Union[pl.DataType, None],
        positions: List[int],
        strand: List[bool],
        context: List[Union[bool, None]],
        count_m: List[int],
        count_total: List[int],
    ): ...
    @staticmethod
    def from_dataframe(
        data: pl.DataFrame,
        check_nulls: bool = True,
        check_sorted: bool = True,
        check_duplicates: bool = True,
        rechunk: bool = True,
        check_single_chr: bool = True,
        chr_values: Union[List[str], None] = None,
    ) -> "BsxBatch": ...
    @staticmethod
    def schema() -> pl.Schema: ...
    @staticmethod
    def empty() -> "BsxBatch": ...
    @staticmethod
    def concat(batches=Sequence["BsxBatch"]) -> "BsxBatch": ...
    def chr(self) -> pl.Series: ...
    def position(self) -> pl.Series: ...
    def strand(self) -> pl.Series: ...
    def context(self) -> pl.Series: ...
    def count_m(self) -> pl.Series: ...
    def count_total(self) -> pl.Series: ...
    def density(self) -> pl.Series: ...
    def column(self, name: BsxColumns) -> pl.Series: ...
    def is_empty(self) -> bool: ...
    def split_at(self, index: int) -> Tuple["BsxBatch", "BsxBatch"]: ...
    def rechunk(self) -> "BsxBatch": ...
    def data(self) -> pl.DataFrame: ...
    def into_dataframe(self) -> pl.DataFrame: ...
    def slice(self, start: int, length: int) -> "BsxBatch": ...
    def add_context_data(self, context_data: Any) -> "BsxBatch":
        # TODO add context data type
        ...
    def extend(self, other: "BsxBatch") -> "BsxBatch": ...
    def extend_unchecked(self, other: "BsxBatch") -> "BsxBatch": ...
    def discretise(
        self, n_fragments: int, method: AggMethod
    ) -> Tuple[List[float], List[float]]: ...
    def partition(
        self, breakpoints: List[int], method: AggMethod
    ) -> Tuple[List[float], List[float]]: ...
    def seqname(self) -> Union[str, None]: ...
    def first_pos(self) -> Union[int, None]: ...
    def last_pos(self) -> Union[int, None]: ...
    def first_genomic_pos(self) -> Union["GenomicPosition", None]: ...
    def last_genomic_pos(self) -> Union["GenomicPosition", None]: ...
    def as_contig(self) -> Union["Contig", None]: ...
    def as_binom(self, mean: float, pvalue, float) -> "BsxBatch": ...
    def into_report(self, report_type: "ReportTypeSchema") -> pl.DataFrame: ...
    def lazy(self) -> "LazyBsxBatch": ...
    def height(self) -> int: ...
    def __len__(self): ...
    def __repr__(self): ...
    def __cmp__(self, other): ...

class ContextData:
    def __init__(self, sequence: bytes): ...
    @staticmethod
    def empty() -> "ContextData": ...
    def is_empty(self) -> bool: ...
    def take(self) -> Tuple[List[int], List[Strand], List[Context]]: ...
    def to_decoded_df(self) -> pl.DataFrame: ...
    def __len__(self): ...

class ReportTypeSchema(Enum):
    Bismark = auto()
    CgMap = auto()
    BedGraph = auto()
    Coverage = auto()

    def col_names(self) -> List[str]: ...
    def schema(self) -> pl.Schema: ...
    def chr_col(self) -> str: ...
    def position_col(self) -> str: ...
    def context_col(self) -> Union[str, None]: ...
    def strand_col(self) -> Union[str, None]: ...
    def need_align(self) -> bool: ...

class LazyBsxBatch:
    def __init__(self, batch: BsxBatch): ...
    def collect(self) -> "BsxBatch": ...
    def filter_pos_lt(self, pos: int) -> "LazyBsxBatch": ...
    def filter_pos_gt(self, pos: int) -> "LazyBsxBatch": ...
    def filter_coverage_gt(self, coverage: int) -> "LazyBsxBatch": ...
    def filter_strand(self, strand: Strand) -> "LazyBsxBatch": ...
    def filter_context(self, context: Context) -> "LazyBsxBatch": ...

class GenomicPosition:
    def __init__(self, seqname: str, position: int): ...
    def __str__(self): ...
    def __repr__(self): ...
    def __add__(self, other): ...
    def __sub__(self, other): ...
    def is_zero(self) -> bool: ...
    @property
    def seqname(self) -> str: ...
    @property
    def position(self) -> int: ...

class Contig:
    @property
    def seqname(self) -> str: ...
    @property
    def start(self) -> int: ...
    @property
    def end(self) -> int: ...
    @property
    def strand(self) -> Strand: ...
    def __init__(self, seqname: str, start: int, end: int, strand: Strand): ...
    @property
    def strand_str(self) -> str: ...
    def length(self) -> int: ...
    def start_gpos(self) -> GenomicPosition: ...
    def end_gpos(self) -> GenomicPosition: ...
    def extend_upstream(self, n: int): ...
    def extend_downstream(self, n: int): ...
    def is_in(self, other: "Contig") -> bool: ...
    def __str__(self): ...
    def __repr__(self): ...

class GffEntryAttributes:
    def __init__(self): ...
    @property
    def id(self) -> Union[str, None]: ...
    @property
    def name(self) -> Union[List[str], None]: ...
    @property
    def alias(self) -> Union[List, None]: ...
    @property
    def parent(self) -> Union[List, None]: ...
    @property
    def other(self) -> Dict[str, str]: ...
    def __repr__(self): ...

class GffEntry:
    def __init__(
        self,
        contig: Contig,
        source: Union[str, None],
        feature_type: Union[str, None],
        score: Union[float, None],
        phase: Union[int, None],
        id: Union[str, None],
    ): ...
    @property
    def id(self) -> str: ...
    @property
    def contig(self) -> Contig: ...
    @property
    def source(self) -> str: ...
    @property
    def feature_type(self) -> str: ...
    @property
    def score(self) -> float: ...
    def phase(self) -> int: ...
    @property
    def attributes(self) -> "GffEntryAttributes": ...
    def __repr__(self): ...

class HcAnnotStore:
    def __init__(self): ...
    @staticmethod
    def from_gff(path: str) -> "HcAnnotStore": ...
    @staticmethod
    def from_bed(path: str) -> "HcAnnotStore": ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get_entry(self, id_u64: int) -> Union[GffEntry, None]: ...
    def get_entries_regex(self, pattern: str) -> List[GffEntry]: ...
    def get_children(self, id_u64: int) -> Union[List[GffEntry], None]: ...
    def get_parent(self, id_u64: int) -> Union[None, GffEntry]: ...
    def genomic_query(self, contig: Contig): ...
    def get_feature_types(self) -> Dict[str, List[int]]: ...
    def add_flanks(self, ids_u64: List[int], flank: int, prefix: str): ...
    def iter(self) -> "HcAnnotStoreIterator": ...
    def __len__(self): ...
    def __repr__(self): ...
    def __iter__(self) -> "HcAnnotStoreIterator": ...
    def init_tree(self): ...
    def init_imap(self): ...

class HcAnnotStoreIterator:
    def __iter__(self): ...
    def __next__(self) -> Union[Tuple[int, GffEntry], None]: ...

class BsxFileReader:
    def __init__(self, file: Union[str, Path, BytesIO]):
        ...

    def get_batch(self, batch_idx: int) -> Union[BsxBatch, None]:
        ...

    def get_batches(self, batch_indices: list[int]) -> List[Union[BsxBatch, None]]:
        ...

    def cache_batches(self, batch_indices: list[int]):
        ...

    @property
    def n_threads(self) -> int:
        ...

    @property
    def blocks_total(self) -> int:
        ...

    def __iter__(self):
        ...

    def __next__(self) -> Union[BsxBatch, None]:
        ...

class BatchIndex:
    def __init__(self):
        ...

    def insert(self, seqname: str, start: int, end: int, batch_idx: int):
        ...

    def find(self, seqname: str, start: int, end: int):
        ...

    def get_chr_order(self) -> list[str]:
        ...

    def get_chr_index(self, chr: str) -> Union[int]:
        ...

    def save(self, filename: Union[str, Path]):
        ...

    @staticmethod
    def load(filename: Union[str, Path]) -> 'BatchIndex':
        ...

    def sort(self, contigs: list[Contig]) -> list[Contig]:
        ...

class IpcCompression(Enum):
    LZ4 = auto()
    ZSTD = auto()

class BsxFileWriter:
    def __init__(
            self,
            sink: Union[str, Path, BytesIO],
            chr_names: list[str],
            compression: Union[IpcCompression, None]
    ):
        ...

    @staticmethod
    def from_sink_and_fai(
            sink: Union[str, Path, BytesIO],
            fai_path: Union[str, Path],
            compression: Union[IpcCompression, None]
    ) -> 'BsxFileWriter':
        ...

    @staticmethod
    def from_sink_and_fasta(
            sink: Union[str, Path, BytesIO],
            fasta_path: Union[str, Path],
            compression: Union[IpcCompression, None]
    ) -> 'BsxFileWriter':
        ...

    def write_batch(self, batch: BsxBatch):
        ...

    def close(self):
        ...

    def __enter__(self) -> 'BsxFileWriter':
        ...

    def __exit__(self, exc_type, exc_val, exc_tb):
        ...

class Compression(Enum):
    No = auto()
    Gz = auto()
    Zstd = auto()
    Lz4 = auto()
    Xz2 = auto()
    Bzip2 = auto()
    Zip = auto()

class ReportReader:
    def __init__(
            self,
            path: Union[str, Path],
            report_type: ReportTypeSchema,
            chunk_size: int = 10_000,
            fasta_path: Union[str, Path, None] = None,
            fai_path: Union[str, Path, None] = None,
            batch_size: int = 100_000,
            low_memory: bool = False,
            compression = Union[Compression, None],
    ):
        ...

    def __iter__(self):
        ...

    def __next__(self) -> Union[BsxBatch, None]:
        ...

class ReportWriter:
    def __init__(
            self,
            sink: Union[str, Path, BytesIO],
            schema: ReportTypeSchema,
            n_threads: int = 1,
            compression: Union[Compression, None] = None,
            compression_level: Union[int, None] = None
    ):
        ...

    def write_batch(self, batch: BsxBatch):
        ...

    def write_df(self, df: pl.DataFrame):
        ...

    def close(self):
        ...

    def __enter__(self) -> 'ReportWriter':
        ...

    def __exit__(self, exc_type, exc_val, exc_tb):
        ...

class FilterOperation:
    @staticmethod
    def PosLt(value: int) -> 'FilterOperation':
        ...
    @staticmethod
    def PosGt(value: int) -> 'FilterOperation':
        ...
    @staticmethod
    def CoverageGt(value: int) -> 'FilterOperation':
        ...
    @staticmethod
    def Strand(value: Strand) -> 'FilterOperation':
        ...
    @staticmethod
    def Context(value: Context) -> 'FilterOperation':
        ...

class RegionReaderIterator:
    def __iter__(self):
        ...

    def __next__(self) -> Union[BsxBatch, None]:
        ...

class RegionReader:
    def __init__(self, file: Union[str, Path, BytesIO]):
        ...

    @classmethod
    def from_reader(cls, reader: BsxFileReader) -> 'RegionReader':
        ...

    def query(self, contig: Contig) -> Union[BsxBatch, None]:
        ...

    def reset(self):
        ...

    def chr_order(self) -> list[str]:
        ...

    def add_filter(self, filter: FilterOperation):
        ...

    def clear_filters(self):
        ...

    def filter_pos_lt(self, value: int):
        ...
    def filter_pos_gt(self, value: int):
        ...
    def filter_coverage_gt(self, value: int):
        ...
    def filter_strand(self, value: Strand):
        ...
    def filter_context(self, value: Context):
        ...
    def index(self) -> 'BatchIndex':
        ...
    def iter_contigs(self, contigs: list[Contig]) -> RegionReaderIterator:
        ...

