from collections.abc import Sequence
from os import PathLike
from types import TracebackType
from typing import BinaryIO, ClassVar, TypeAlias, final

import polars as pl
from typing_extensions import disjoint_base

__all__ = [
    "AggMethod",
    "BatchIndex",
    "BsxBatch",
    "BsxColumns",
    "BsxFileReader",
    "BsxFileWriter",
    "Compression",
    "Context",
    "ContextData",
    "Contig",
    "FilterOperation",
    "GenomicPosition",
    "GffEntry",
    "GffEntryAttributes",
    "HcAnnotStore",
    "HcAnnotStoreIterator",
    "IpcCompression",
    "LazyBsxBatch",
    "RegionReader",
    "RegionReaderIterator",
    "ReportReader",
    "ReportTypeSchema",
    "ReportWriter",
    "Strand",
    "merge_metagene_values",
]

_Path: TypeAlias = str | PathLike[str]
_Sink: TypeAlias = _Path | BinaryIO
_DType: TypeAlias = pl.DataType | type[pl.DataType]

# PyO3 enums are native classes, not subclasses of enum.Enum.
@final
class Strand:
    Forward: ClassVar[Strand]
    Reverse: ClassVar[Strand]
    Null: ClassVar[Strand]
    @property
    def name(self) -> str: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class Context:
    CG: ClassVar[Context]
    CHG: ClassVar[Context]
    CHH: ClassVar[Context]
    @property
    def name(self) -> str: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class BsxColumns:
    Chr: ClassVar[BsxColumns]
    Position: ClassVar[BsxColumns]
    Strand: ClassVar[BsxColumns]
    Context: ClassVar[BsxColumns]
    CountM: ClassVar[BsxColumns]
    CountTotal: ClassVar[BsxColumns]
    Density: ClassVar[BsxColumns]
    @staticmethod
    def schema() -> dict[str, _DType]: ...
    def as_str(self) -> str: ...
    @staticmethod
    def colnames() -> list[str]: ...
    @staticmethod
    def has_name(name: str) -> bool: ...
    def __int__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class AggMethod:
    Mean: ClassVar[AggMethod]
    GeometricMean: ClassVar[AggMethod]
    Median: ClassVar[AggMethod]
    Max: ClassVar[AggMethod]
    Min: ClassVar[AggMethod]
    def __int__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class BsxBatch:
    def __new__(
        cls: type[BsxBatch],
        chr: str,
        chr_dtype: _DType | None,
        positions: Sequence[int],
        strand: Sequence[bool],
        context: Sequence[bool | None],
        count_m: Sequence[int],
        count_total: Sequence[int],
    ) -> BsxBatch: ...
    @staticmethod
    def from_dataframe(
        data: pl.DataFrame,
        check_nulls: bool = True,
        check_sorted: bool = True,
        check_duplicates: bool = True,
        rechunk: bool = True,
        check_single_chr: bool = True,
        chr_values: Sequence[str] | None = None,
    ) -> BsxBatch: ...
    @staticmethod
    def schema() -> dict[str, _DType]: ...
    @staticmethod
    def empty(chr_dtype: _DType | None = None) -> BsxBatch: ...
    @staticmethod
    def concat(batches: Sequence[BsxBatch]) -> BsxBatch: ...
    def chr(self) -> pl.Series: ...
    def position(self) -> pl.Series: ...
    def strand(self) -> pl.Series: ...
    def context(self) -> pl.Series: ...
    def count_m(self) -> pl.Series: ...
    def count_total(self) -> pl.Series: ...
    def density(self) -> pl.Series: ...
    def column(self, name: BsxColumns) -> pl.Series: ...
    def is_empty(self) -> bool: ...
    def split_at(self, index: int) -> tuple[BsxBatch, BsxBatch]: ...
    def rechunk(self) -> BsxBatch: ...
    def data(self) -> pl.DataFrame: ...
    def into_dataframe(self) -> pl.DataFrame: ...
    def slice(self, start: int, length: int) -> BsxBatch: ...
    def add_context_data(self, context_data: ContextData) -> BsxBatch: ...
    def extend(self, other: BsxBatch) -> None: ...
    def extend_unchecked(self, other: BsxBatch) -> None: ...
    def shrink(
        self, min_size: int, beta: float | None = None
    ) -> tuple[list[float], list[float]]: ...
    def discretise(
        self, n_fragments: int, method: AggMethod
    ) -> tuple[list[float], list[float]]: ...
    def partition(
        self, breakpoints: Sequence[int], method: AggMethod
    ) -> tuple[list[float], list[float]]: ...
    def normalized(self) -> tuple[list[float], list[float]]: ...
    def seqname(self) -> str | None: ...
    def first_pos(self) -> int | None: ...
    def last_pos(self) -> int | None: ...
    def first_genomic_pos(self) -> GenomicPosition | None: ...
    def last_genomic_pos(self) -> GenomicPosition | None: ...
    def as_contig(self) -> Contig | None: ...
    def as_binom(self, mean: float, pvalue: float) -> BsxBatch: ...
    def into_report(self, report_type: ReportTypeSchema) -> pl.DataFrame: ...
    def lazy(self) -> LazyBsxBatch: ...
    def height(self) -> int: ...
    def __len__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class ContextData:
    def __new__(
        cls: type[ContextData], sequence: bytes | Sequence[int]
    ) -> ContextData: ...
    @staticmethod
    def empty() -> ContextData: ...
    def is_empty(self) -> bool: ...
    def take(self) -> tuple[list[int], list[Strand], list[Context]]: ...
    def to_decoded_df(self) -> pl.DataFrame: ...
    def __len__(self) -> int: ...

@final
class ReportTypeSchema:
    Bismark: ClassVar[ReportTypeSchema]
    CgMap: ClassVar[ReportTypeSchema]
    BedGraph: ClassVar[ReportTypeSchema]
    Coverage: ClassVar[ReportTypeSchema]
    def col_names(self) -> list[str]: ...
    def schema(self) -> dict[str, _DType]: ...
    def chr_col(self) -> str: ...
    def position_col(self) -> str: ...
    def context_col(self) -> str | None: ...
    def strand_col(self) -> str | None: ...
    def need_align(self) -> bool: ...
    def __int__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class LazyBsxBatch:
    def __new__(cls: type[LazyBsxBatch], batch: BsxBatch) -> LazyBsxBatch: ...
    def collect(self) -> BsxBatch: ...
    def filter_pos_lt(self, pos: int) -> LazyBsxBatch: ...
    def filter_pos_gt(self, pos: int) -> LazyBsxBatch: ...
    def filter_coverage_gt(self, coverage: int) -> LazyBsxBatch: ...
    def filter_strand(self, strand: Strand) -> LazyBsxBatch: ...
    def filter_context(self, context: Context) -> LazyBsxBatch: ...

@final
class GenomicPosition:
    seqname: str
    position: int
    def __new__(
        cls: type[GenomicPosition], seqname: str, position: int
    ) -> GenomicPosition: ...
    def __add__(self, value: GenomicPosition, /) -> GenomicPosition | None: ...
    def __sub__(self, value: GenomicPosition, /) -> GenomicPosition | None: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __lt__(self, value: GenomicPosition, /) -> bool: ...
    def __le__(self, value: GenomicPosition, /) -> bool: ...
    def __gt__(self, value: GenomicPosition, /) -> bool: ...
    def __ge__(self, value: GenomicPosition, /) -> bool: ...
    def is_zero(self) -> bool: ...

@final
class Contig:
    seqname: str
    start: int
    end: int
    strand: Strand
    def __new__(
        cls: type[Contig], seqname: str, start: int, end: int, strand: Strand
    ) -> Contig: ...
    @property
    def strand_str(self) -> str: ...
    def length(self) -> int: ...
    def start_gpos(self) -> GenomicPosition: ...
    def end_gpos(self) -> GenomicPosition: ...
    def extend_upstream(self, length: int) -> None: ...
    def extend_downstream(self, length: int) -> None: ...
    def is_in(self, other: Contig) -> bool: ...
    def is_empty(self) -> bool: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __lt__(self, value: Contig, /) -> bool: ...
    def __le__(self, value: Contig, /) -> bool: ...
    def __gt__(self, value: Contig, /) -> bool: ...
    def __ge__(self, value: Contig, /) -> bool: ...

@final
class GffEntryAttributes:
    def __new__(cls: type[GffEntryAttributes]) -> GffEntryAttributes: ...
    @property
    def id(self) -> str | None: ...
    @property
    def name(self) -> list[str] | None: ...
    @property
    def alias(self) -> list[str] | None: ...
    @property
    def parent(self) -> list[str] | None: ...
    @property
    def other(self) -> dict[str, str]: ...

@final
class GffEntry:
    def __new__(
        cls: type[GffEntry],
        contig: Contig,
        source: str | None = None,
        feature_type: str | None = None,
        score: float | None = None,
        phase: int | None = None,
        id: str | None = None,
    ) -> GffEntry: ...
    @property
    def id(self) -> str: ...
    @property
    def contig(self) -> Contig: ...
    @property
    def source(self) -> str: ...
    @property
    def feature_type(self) -> str: ...
    @property
    def score(self) -> float | None: ...
    @property
    def phase(self) -> int | None: ...
    @property
    def attributes(self) -> GffEntryAttributes: ...

@final
class HcAnnotStore:
    def __new__(cls: type[HcAnnotStore]) -> HcAnnotStore: ...
    @staticmethod
    def from_gff(path: _Path) -> HcAnnotStore: ...
    @staticmethod
    def from_bed(path: _Path) -> HcAnnotStore: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def insert(self, entry: GffEntry) -> int: ...
    def get_entry(self, id_u64: int) -> GffEntry | None: ...
    def get_entries_regex(self, pattern: str) -> list[GffEntry]: ...
    def get_children(self, id_u64: int) -> list[int] | None: ...
    def get_parent(self, id_u64: int) -> int | None: ...
    def genomic_query(self, contig: Contig) -> list[int]: ...
    def get_feature_types(self) -> dict[str, list[int]]: ...
    def add_flanks(self, ids_u64: Sequence[int], flank: int, prefix: str) -> None: ...
    def iter(self) -> HcAnnotStoreIterator: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> HcAnnotStoreIterator: ...
    def init_tree(self) -> None: ...
    def init_imap(self) -> None: ...

@final
class HcAnnotStoreIterator:
    def __iter__(self) -> HcAnnotStoreIterator: ...
    def __next__(self) -> tuple[int, GffEntry]: ...

@final
class BsxFileReader:
    # File objects need a real descriptor for memory mapping; BytesIO is unsupported.
    def __new__(cls: type[BsxFileReader], file: _Sink) -> BsxFileReader: ...
    def get_batch(self, batch_idx: int) -> BsxBatch | None: ...
    def get_batches(self, batch_indices: Sequence[int]) -> list[BsxBatch | None]: ...
    def cache_batches(self, batch_indices: Sequence[int]) -> None: ...
    @property
    def n_threads(self) -> int: ...
    @property
    def blocks_total(self) -> int: ...
    def __iter__(self) -> BsxFileReader: ...
    def __next__(self) -> BsxBatch: ...

@final
class BatchIndex:
    def __new__(cls: type[BatchIndex]) -> BatchIndex: ...
    def insert(self, seqname: str, start: int, end: int, batch_idx: int) -> None: ...
    def find(self, seqname: str, start: int, end: int) -> list[int] | None: ...
    def get_chr_order(self) -> list[str]: ...
    def get_chr_index(self, chr: str) -> int | None: ...
    def save(self, filename: _Path) -> None: ...
    @staticmethod
    def load(filename: _Path) -> BatchIndex: ...
    def sort(self, contigs: Sequence[Contig]) -> list[Contig]: ...

@final
class IpcCompression:
    LZ4: ClassVar[IpcCompression]
    ZSTD: ClassVar[IpcCompression]
    def __int__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class BsxFileWriter:
    def __new__(
        cls: type[BsxFileWriter],
        sink: _Sink,
        chr_names: Sequence[str],
        compression: IpcCompression | None = None,
    ) -> BsxFileWriter: ...
    @staticmethod
    def from_sink_and_fai(
        sink: _Sink, fai_path: _Path, compression: IpcCompression | None = None
    ) -> BsxFileWriter: ...
    @staticmethod
    def from_sink_and_fasta(
        sink: _Sink, fasta_path: _Path, compression: IpcCompression | None = None
    ) -> BsxFileWriter: ...
    def write_batch(self, batch: BsxBatch) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> BsxFileWriter: ...
    def __exit__(
        self,
        _exc_type: type[BaseException] | None,
        _exc_value: BaseException | None,
        _traceback: TracebackType | None,
    ) -> None: ...

@final
class Compression:
    No: ClassVar[Compression]
    Gz: ClassVar[Compression]
    Zstd: ClassVar[Compression]
    Lz4: ClassVar[Compression]
    Xz2: ClassVar[Compression]
    Bzip2: ClassVar[Compression]
    Zip: ClassVar[Compression]
    def __int__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...

@final
class ReportReader:
    def __new__(
        cls: type[ReportReader],
        path: _Path,
        report_type: ReportTypeSchema,
        chunk_size: int = 10_000,
        fasta_path: _Path | None = None,
        fai_path: _Path | None = None,
        batch_size: int = 100_000,
        low_memory: bool = False,
        compression: Compression | None = None,
    ) -> ReportReader: ...
    def __iter__(self) -> ReportReader: ...
    def __next__(self) -> BsxBatch: ...

@final
class ReportWriter:
    def __new__(
        cls: type[ReportWriter],
        sink: _Sink,
        schema: ReportTypeSchema,
        n_threads: int = 1,
        compression: Compression | None = None,
        compression_level: int | None = None,
    ) -> ReportWriter: ...
    def write_batch(self, batch: BsxBatch) -> None: ...
    def write_df(self, df: pl.DataFrame) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> ReportWriter: ...
    def __exit__(
        self,
        _exc_type: type[BaseException] | None,
        _exc_value: BaseException | None,
        _traceback: TracebackType | None,
    ) -> None: ...

_Strand = Strand
_Context = Context

@disjoint_base
class FilterOperation:
    @final
    class PosLt(FilterOperation):
        __match_args__: ClassVar[tuple[str]] = ("value",)
        def __new__(
            cls: type[FilterOperation.PosLt], value: int
        ) -> FilterOperation.PosLt: ...
        @property
        def value(self) -> int: ...

    @final
    class PosGt(FilterOperation):
        __match_args__: ClassVar[tuple[str]] = ("value",)
        def __new__(
            cls: type[FilterOperation.PosGt], value: int
        ) -> FilterOperation.PosGt: ...
        @property
        def value(self) -> int: ...

    @final
    class CoverageGt(FilterOperation):
        __match_args__: ClassVar[tuple[str]] = ("value",)
        def __new__(
            cls: type[FilterOperation.CoverageGt], value: int
        ) -> FilterOperation.CoverageGt: ...
        @property
        def value(self) -> int: ...

    @final
    class Strand(FilterOperation):
        __match_args__: ClassVar[tuple[str]] = ("value",)
        def __new__(
            cls: type[FilterOperation.Strand], value: _Strand
        ) -> FilterOperation.Strand: ...
        @property
        def value(self) -> _Strand: ...

    @final
    class Context(FilterOperation):
        __match_args__: ClassVar[tuple[str]] = ("value",)
        def __new__(
            cls: type[FilterOperation.Context], value: _Context
        ) -> FilterOperation.Context: ...
        @property
        def value(self) -> _Context: ...

@final
class RegionReaderIterator:
    def __iter__(self) -> RegionReaderIterator: ...
    def __next__(self) -> BsxBatch: ...

@final
class RegionReader:
    def __new__(cls: type[RegionReader], file: _Sink) -> RegionReader: ...
    @classmethod
    def from_reader(cls, reader: BsxFileReader) -> RegionReader: ...
    def query(self, contig: Contig) -> BsxBatch | None: ...
    def reset(self) -> None: ...
    def chr_order(self) -> list[str]: ...
    def add_filter(self, filter: FilterOperation) -> None: ...
    def clear_filters(self) -> None: ...
    def filter_pos_lt(self, value: int) -> None: ...
    def filter_pos_gt(self, value: int) -> None: ...
    def filter_coverage_gt(self, value: int) -> None: ...
    def filter_strand(self, value: Strand) -> None: ...
    def filter_context(self, value: Context) -> None: ...
    def index(self) -> BatchIndex: ...
    def iter_contigs(self, contigs: Sequence[Contig]) -> RegionReaderIterator: ...

def merge_metagene_values(
    positions: Sequence[Sequence[float]], densities: Sequence[Sequence[float]]
) -> tuple[list[float], list[float]]: ...
