repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: check-added-large-files
  - id: detect-private-key

- repo: https://github.com/crate-ci/typos
  rev: v1.32.0
  hooks:
    - id: typos

# - repo: https://github.com/est31/cargo-udeps
#   rev: v0.1.47
#   hooks:
#     - id: cargo udeps
#       args: ["--all-features"]

- repo: local
  hooks:
  - id: rust-format
    name: rustfmt
    entry: just format
    language: system

- repo: local
  hooks:
  - id: rust-test
    name: nextest
    entry: just rs-test-fast
    language: system

default_language_version:
  rust: stable
  python: python3.12
