[package]
name = "bsxplorer2"
version = "0.1.0"
edition = "2021"
authors = ["shitohana"]


[features]
python = ["dep:pyo3", "dep:pyo3-polars"]
rlang = ["dep:extendr-api"]

[dependencies]
arrow = "53.1.0"
bzip2 = "0.4.4"
flate2 = "^1.0"
tar = "0.4.42"
xz2 = "0.1.7"
zstd = "0.13.2"
hashbrown = { version = "=0.14.5", features = ["raw"] }
bio = "2.0.3"
zip = "=2.2.0"
itertools = "0.13.0"
rayon = "1.10"
pyo3 = { version = "=0.21.0", features = ["extension-module"], optional = true}
pyo3-polars = { version = "0.18.0", optional = true }
extendr-api = { version = '*', optional = true}

[lib]
name="bsx_rs"
crate-type = ["cdylib"]

[dependencies.polars]
version = "0.44.2"
features = [
    # Performance
    "performant",
    # Data types
    "dtype-categorical",
    "dtype-struct",
    "dtype-array",
    # Lazy
    "lazy",
    # IO
    "csv",
    "decompress",
    "ipc",
    "ipc_streaming",
    "streaming",
    # DataFrame operations
    "dataframe_arithmetic",
    "partition_by",
    "asof_join",
    # Expressions
    "is_in",
    "concat_str",
    "rank",
    "list_eval",
    "list_count",
    "list_any_all",
    "search_sorted",
    # Misc
    "fmt",
]
