[package]
name = "bsxplorer2"
version = "0.1.0"
edition = "2021"
authors = ["shitohana"]

[workspace]
members = ["console"]

[lib]
path = "src/lib.rs"

[features]
default = ["plots"]
plots = ["plotly", "z_table", "yew", "yew-plotly"]

[dev-dependencies]
rand_chacha = "=0.3.1"
quickcheck = "*"
criterion = { version = "0.5.1", features = ["html_reports"] }
plotters = { version = "0.3.7", default-features = false, features = [] }

[dependencies]
# Utility
anyhow = "1.0.91"
assert_approx_eq = "1.1.0"
crossbeam = "0.8.4"
hashbrown = { version = "=0.14.5", features = ["raw"] }
itertools = "0.14.0"
memmap2 = "0.9.5"
num = "0.4.3"
once_cell = "1.20.3"
rayon = "1.10"
tempfile = "3.15.0"
uuid = { version = "1.12.1", features = ["serde"] }

# Logging
log = "0.4.22"
pretty_env_logger = "0.5.0"

# Serde
bincode = "1.3.3"
serde = "1.0.217"
serde_json = "1"

# Stats
console = "0.15"

adjustp = "0.1.6"
histogram = "0.11.2"
rand = { version = "=0.8.5", features = ["std", "std_rng"] }
rand_distr = "=0.4.3"
rand_xoshiro = "0.7.0"
argmin = "0.10.0"
ndarray = { version = "0.15.4", features = ["serde"] }
statrs = "0.18.0"

# Bio
bio = "2.0.3"
bio-types = "1.0.4"
noodles = { version = "0.90.0", features = ["fasta"] }

# Plots
plotly = { version = "0.12.1", optional = true }
yew = { version = "0.21", features = ["csr"], optional = true }
yew-plotly = { version = "0.3.0", optional = true }
z_table = { version = "0.1.5", optional = true }

[dependencies.polars]
version = "=0.45.0"
default-features = false
features = [
    # Performance
    "performant",
    # Data types
    "dtype-i16",
    "dtype-u8",
    "dtype-i8",
    "dtype-u16",
    "dtype-categorical",
    "dtype-struct",
    "dtype-array",
    # Lazy
    "lazy",
    # IO
    "csv",
    "decompress",
    "ipc",
    "ipc_streaming",
    "streaming",
    # DataFrame operations
    "dataframe_arithmetic",
    "partition_by",
    "asof_join",
    "polars-ops",
    # Expressions
    "strings",
    "is_in",
    "round_series",
    "concat_str",
    "rank",
    "list_eval",
    "list_count",
    "list_any_all",
    "search_sorted",
]

[dependencies.polars-arrow-format]
version = "0.1.0"
