[package]
name = "bsxplorer2"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = "53.1.0"
bzip2 = "0.4.4"
flate2 = "1.0.34"
polars-core = "0.43.1"
tar = "0.4.42"
xz2 = "0.1.7"
zstd = "0.13.2"
hashbrown = { version = "0.14.5", features = ["raw"] }
bio = "2.0.3"
zip = "=2.2.0"

[dependencies.polars]
version = "0.43.1"
features = [
    "csv",
    "partition_by",
    "performant",
    "lazy",
    "streaming",
    "ipc",
    "dataframe_arithmetic",
    "asof_join",
    "is_in",
    "concat_str",
    "rank",
    "list_eval",
    "list_count",
    "search_sorted",
    "fmt",
    "dtype-categorical"
]
