[package]
name = "bsxplorer2_dev"
version = "0.1.0"
edition = "2021"
authors = ["shitohana"]

[[bin]]
name = "bsxplorer2_dev"
path = "src/main.rs"

[workspace]
members = [
    "bsx_rs",
    "bsxplorer2"
]

[dependencies]
bsx_rs = { path = "./bsx_rs"}
