[project]
name = "bsxplorer2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"
