[package]
name = "bsxplorer2-py"
authors.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
version.workspace = true
edition.workspace = true
readme.workspace = true
license = "MIT"

[lib]
crate-type = ["cdylib"]
name = "bsx2"
path = "rust/lib.rs"

[features]
nightly = ["bsxplorer2/performant_nightly"]

[dependencies]
bsxplorer2 = { version = "0.2.3", features = ["compression", "performant", "tools"] }
pyo3 = { version = "=0.22.4", features = ["extension-module", "anyhow", "either"] }
# We need to use the same version of polars as in the Rust code
pyo3-polars = {version = "=0.19.0", features = ["dtype-full", "lazy"]}
pyo3-file = "0.9.0"
polars.workspace = true
slotmap.workspace = true
[profile.release]
debug = true
strip = "none"
