[package]
name = "bsx2"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "bsx2"

[dependencies]
bsxplorer2 = { path = "../bsxplorer2", features = ["compression", "performant"] }
pyo3 = { version = "=0.22.4", features = ["extension-module", "anyhow", "either"] }
# We need to use the same version of polars as in the Rust code
pyo3-polars = "=0.19.0"
pyo3-file = "0.9.0"