[package]
name = "bsx2"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
name = "bsx2"

[dependencies]
bsxplorer2 = { path = "../bsxplorer2" }
pyo3 = { version = "=0.22.4", features = ["extension-module"] }
# We need to use the same version of polars as in the Rust code
pyo3-polars = "=0.19.0"