[package]
name = "bsxplorer2"
version = "0.1.0"
edition = "2021"

[lib]
name = "_lib"
path = "rust/lib.rs"
crate-type = ["cdylib"]

[dependencies]
bsx_rs = { path = "../bsx_rs"}

pyo3 = { version = "0.21", features = ["extension-module"]}

[dependencies.polars]
version = "0.44.2"
features = [
    # Performance
    "performant",
    # Data types
    "dtype-categorical",
    "dtype-struct",
    "dtype-array",
    # Lazy
    "lazy",
    # IO
    "csv",
    "decompress",
    "ipc",
    "ipc_streaming",
    "streaming",
    # DataFrame operations
    "dataframe_arithmetic",
    "partition_by",
    "asof_join",
    # Expressions
    "strings",
    "is_in",
    "concat_str",
    "rank",
    "list_eval",
    "list_count",
    "list_any_all",
    "search_sorted",
    # Misc
    "fmt",
]

[dependencies.pyo3-polars]
version = "0.18.0"
features = [
    "dtype-array",
    "dtype-categorical",
    "dtype-full",
    "dtype-struct",
    "derive"
]
