[package]
name = "bsxplorer-ci"
version = "0.1.1"
edition = "2021"

[dependencies]
bsxplorer-lib = { path = "../rust" }

clap = { version = "4.1", features = ["derive"] }
console = "0.15"
csv = { version = "1.3.1" }
dialoguer = "0.11.0"
glob = "0.3"
indicatif = "0.17.11"
serde = "1.0.218"
wild = "2.0"

[[bin]]
name = "bsxplorer"
path = "src/main.rs"
