[package]
name = "bsxplorer-ci"
version = "0.1.1"
edition = "2021"

[dependencies]
bsxplorer-lib = { path = "../rust" }

clap = { version = "4.1", features = ["derive"] }
wild = "2.0"
glob = "0.3"
console = "0.15"
dialoguer = "0.11.0"
indicatif = "0.17.11"
tempfile = "3.16.0"
serde = "1.0.217"
bincode = { version = "1.3.3" }
statrs = "0.18.0"
rayon = "1.10.0"
adjustp = "0.1.6"
anyhow = "1.0.91"