[package]
name = "bsxplorer-ci"
version = "0.1.2-post1"
edition = "2021"
authors = ["shitohana (kyudytskiy@gmail.com)"]
license = "MIT"
description = "A high-performance tool for bisulfite sequencing data analysis and DNA methylation research"
repository = "https://github.com/shitohana/bsxplorer2"
keywords = ["bioinformatics", "methylation", "bisulfite", "epigenetics", "genomics"]
categories = ["science", "data-structures", "algorithms", "mathematics"]
readme = "README.md"

[dependencies]
bsxplorer2 = { path = "../bsxplorer2", features = ["compression", "console"], default-features = false }

clap = { version = "4.1", features = ["derive"] }
console = "0.15"
csv = { version = "1.3.1" }
dialoguer = "0.11.0"
glob = "0.3"
indicatif = "0.17.11"
serde = "1.0.218"
wild = "2.0"

[[bin]]
name = "bsxplorer"
path = "src/main.rs"
